#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Takuto Suzukawa
# SPDX-License-Indentifier: GPL-3.0

import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
    	ans += float(line)

print(ans)

